### PR TITLE
Add release workflow

### LINKED ISSUE #6: [Feature] Enable the intermediary Pod data mover to be configurable
### Problem Statement

The intermediary Pod responsible for the copy operation in case of scale downs is not currently configurable. Many users will need to configure this Pod according to their needs so it passes security guidelines.

### Solution Description

Allow the intermediary Pod copier to be configured in the most common ways including, but not limited to,:
* image
* name
* metadata

### Alternatives

_No response_

### Additional Context

_No response_

### Troubleshooting

- [x] I have searched other issues in this repository and mine is not recorded.

### LINKED ISSUE #7: CI process for builds
Need to establish a CI pipeline for builds and releases. `ko` can be used as an alternative to Docker which is slimmer and uses a minimal base image similar to build packs.

Ex.:

```sh
KO_DOCKER_REPO=ko.local ko build ./cmd/diskautoscaler/ --preserve-import-paths --tags=latest --platform=linux/amd64
```

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: Chip Zoller <chipzoller@gmail.com>

## What does this PR change?

* Adds a new release workflow using [ko](https://ko.build/) and provides software supply chain security by default.
  * This workflow publishes images to gcr.io/kubecost1 automatically upon new tagged releases.
  * Uploads as release assets the SBOM, vuln scan, image signature, and a version of `install.yaml` with the digest from the release process.
  * Uses all modern software supply chain security techniques including image signing and attestations of SBOM, vulnerability scan, and SLSA provenance.
  * Uses OIDC and GCP Workload Identity Federation to support keyless access for all operations against GCR.
* Removes the Dockerfile
* Adds a new SECURITY.md describing what security assets are available and how to perform verification.
* Lints/normalizes the `install.yaml` manifest as well as updates the `image` string to use the `latest` tag which will become available after the first and any subsequent release actions.
* Minor typo fix in README
* Comments out main build recipe in Justfile for later refactoring to use `ko`

## Does this PR rely on any other PRs?

No

## How does this PR impact users?

CI only but allows users to verify modern software supply chain security for this project.

## Links to Issues or tickets this PR addresses or fixes

Closes #7

## What risks are associated with merging this PR? What is required to fully test this PR?

The first release build needs to be triggered after this is accepted so the new image and its assets are pushed into the correct repository.

## How was this PR tested?

In a separate repo.

### CODE REVIEW

**Comment by chipzoller** [comment]
Not to self:  once merged and the first release cut, need to update manifest to use latest tag.

**Comment by chipzoller** [comment]
@avrodrigues5, can we add ldflags s and w to further reduce build size? Just may be impacted if needing to run a debugger. Any concerns there?

**Comment by avrodrigues5** [comment]
@chipzoller high level this looks good. 

Few questions:

1. Where are SBOM, vulnerabiliy scan etc available for each image? I see a note saying also available offline, can i go check it or its during the build process the output get emitted in the build logs?  
2. Ko looks good just by reading it . is build size reduction a P0, im not sure what impact -s and -w ldflags would have in future debugging. I recommend holding it off if build size reduction is not a priority at the time wdyt?

**Comment by chipzoller** [comment]
1. SBOM and vuln scans are attached as attestations to the image in the registry and also available as release assets.

2. Use of those flags drops the size by about 50%, and since we probably don't need a tice debugging at this point my suggestion would be to add them until we see a case where this presents a problem.

**Comment by chipzoller** [comment]
@avrodrigues5, I added the `.ko.yaml` with the ldflags set.

**Comment by chipzoller** [comment]
[All green](https://github.com/kubecost/disk-autoscaler/actions/runs/9078443349). Release [0.0.18](https://github.com/kubecost/disk-autoscaler/releases/tag/0.0.18) is live.

**Pull request merged**
